[package]
name = "card-id-recorder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
umya-spreadsheet = "1.0.0"
pcsc = "2.8.0"
hex = "0.4.3"
serde = { version = "1.0.188", features = ["derive"] }
toml = "0.7.6"
